
#ifndef _io_H_
#define _io_H_
//end of add your includes here
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
} // extern "C"
#endif

#ifdef CONSOLE_PARSER
extern boolean input_kb(int k);
extern boolean input_cmd_str(char* cmd);
#endif


//generated by acceleo

#define MOTOR 8 
#define SB 9
#define FB 10
#define M 11



 // generated by acceleo
	extern PROGMEM const char s_fb_start[];
	extern PROGMEM const char s_master_start[];
 // generated by acceleo
	extern PROGMEM const char s_master_stop[];
	extern PROGMEM const char s_sb_start[];
 // generated by acceleo
	extern PROGMEM const char s_sb_stop[];
 // generated by acceleo
	extern PROGMEM const char s_m_start[];
	extern PROGMEM const char s_fb_stop[];
 // generated by acceleo
	extern PROGMEM const char s_m_stop[];
	extern PROGMEM const char s_all_start[];
 // generated by acceleo
	extern PROGMEM const char s_all_stop[];


 // generated by acceleo
	extern boolean ev_fb_start;
	extern boolean ev_master_start;
 // generated by acceleo
	extern boolean ev_master_stop;
	extern boolean ev_sb_start;
 // generated by acceleo
	extern boolean ev_sb_stop;
 // generated by acceleo
	extern boolean ev_m_start;
	extern boolean ev_fb_stop;
 // generated by acceleo
	extern boolean ev_m_stop;
	extern boolean ev_all_start;
 // generated by acceleo
	extern boolean ev_all_stop;

//extern boolean exec_cmd_sm(char* cmd);
extern void out_nu(char* ouputName, boolean value);
void out(int outp, boolean value, int i);
extern void resetEvents();
extern void init_io();
extern void acquireInputs();
void resetInputs();
extern void masterStart();
extern void applyOutputs_nu();





#endif

