interface IO:
var MOTOR : boolean
var SB : boolean
var FB: boolean
var M: boolean
in event master_start
in event master_stop
in event sb_start
in event sb_stop
in event fb_stop
in event fb_start
in event m_start
in event m_stop
in event all_start
in event all_stop
16
88
org.yakindu.sct.model.sgraph.impl.StatechartImpl@b4bc72 (specification: interface IO:
var MOTOR : boolean
var SB : boolean
var FB: boolean
var M: boolean
in event master_start
in event master_stop
in event sb_start
in event sb_stop
in event fb_stop
in event fb_start
in event m_start
in event m_stop
in event all_start
in event all_stop) (namespace: null, name: default, documentation: null)org.yakindu.sct.model.sgraph.impl.StatechartImpl@b4bc72 (specification: interface IO:
var MOTOR : boolean
var SB : boolean
var FB: boolean
var M: boolean
in event master_start
in event master_stop
in event sb_start
in event sb_stop
in event fb_stop
in event fb_start
in event m_start
in event m_stop
in event all_start
in event all_stop) (namespace: null, name: default, documentation: null)org.yakindu.sct.model.sgraph.impl.StatechartImpl@b4bc72 (specification: interface IO:
var MOTOR : boolean
var SB : boolean
var FB: boolean
var M: boolean
in event master_start
in event master_stop
in event sb_start
in event sb_stop
in event fb_stop
in event fb_start
in event m_start
in event m_stop
in event all_start
in event all_stop) (namespace: null, name: default, documentation: null)org.yakindu.sct.model.sgraph.impl.StatechartImpl@b4bc72 (specification: interface IO:
var MOTOR : boolean
var SB : boolean
var FB: boolean
var M: boolean
in event master_start
in event master_stop
in event sb_start
in event sb_stop
in event fb_stop
in event fb_start
in event m_start
in event m_stop
in event all_start
in event all_stop) (namespace: null, name: default, documentation: null)org.yakindu.sct.model.sgraph.impl.StatechartImpl@b4bc72 (specification: interface IO:
var MOTOR : boolean
var SB : boolean
var FB: boolean
var M: boolean
in event master_start
in event master_stop
in event sb_start
in event sb_stop
in event fb_stop
in event fb_start
in event m_start
in event m_stop
in event all_start
in event all_stop) (namespace: null, name: default, documentation: null)
      Boolean :  MOTOR 
      Boolean :  boolean
var SB 
      Boolean :  boolean
var FB
      Boolean :  boolean
var M
'substring operation'.substring(11, 19)


----------------------------STATE TEST --------------------------


	STATE5
	STATE1
	STATE4
	STATE3
	STATE6
	STATE2


------------------------------- Target Entry Test ---------------------------


	STATE1


--------------------------------Test Specification of state -----------------


	out(M,true
entry/
IO.FB ,false
entry/
IO.MOTOR,false
entry/
IO.SB,false,-1);
	out(MOTOR,false
entry/
IO.SB, false
entry/
IO.FB,false
entry/
IO.M,false,-1);
	out(FB,true
entry/
IO.M,false
entry/
IO.SB,false
entry/
IO.MOTOR,false,-1);
	out(SB,true
entry/
IO.M,false
entry/
IO.FB ,false
entry/
IO.MOTOR,false,-1);
	out(M,true
entry/
IO.FB ,true
entry/
IO.MOTOR,true
entry/
IO.SB,true,-1);
	out(MOTOR,true
entry/
IO.SB,false
entry/
IO.M,false
entry/
IO.FB,false,-1);
--------------------------------------------------TEST DE 3 ETAT -----------------------------------------------


 // generated by acceleo 

  /** Les entree sortie : master_startfb_start**/ 
		boolean fb_start = false;
		boolean ev_fb_start=false;
		boolean prior_fb_start = false;
		
		PROGMEM const char s_fb_start[] = "fb_start";
	
  /** Les entree sortie : master_startfb_start**/ 
		boolean master_start = false;
		boolean ev_master_start=false;
		boolean prior_master_start = false;
		
		PROGMEM const char s_master_start[] = "master_start";
	
 // generated by acceleo 

  /** Les entree sortie : sb_startmaster_stop**/ 
		boolean master_stop = false;
		boolean ev_master_stop=false;
		boolean prior_master_stop = false;
		
		PROGMEM const char s_master_stop[] = "master_stop";
	
  /** Les entree sortie : sb_startmaster_stop**/ 
		boolean sb_start = false;
		boolean ev_sb_start=false;
		boolean prior_sb_start = false;
		
		PROGMEM const char s_sb_start[] = "sb_start";
	
 // generated by acceleo 

  /** Les entree sortie : sb_stop**/ 
		boolean sb_stop = false;
		boolean ev_sb_stop=false;
		boolean prior_sb_stop = false;
		
		PROGMEM const char s_sb_stop[] = "sb_stop";
	
 // generated by acceleo 

  /** Les entree sortie : fb_stopm_start**/ 
		boolean m_start = false;
		boolean ev_m_start=false;
		boolean prior_m_start = false;
		
		PROGMEM const char s_m_start[] = "m_start";
	
  /** Les entree sortie : fb_stopm_start**/ 
		boolean fb_stop = false;
		boolean ev_fb_stop=false;
		boolean prior_fb_stop = false;
		
		PROGMEM const char s_fb_stop[] = "fb_stop";
	
 // generated by acceleo 

  /** Les entree sortie : all_startm_stop**/ 
		boolean m_stop = false;
		boolean ev_m_stop=false;
		boolean prior_m_stop = false;
		
		PROGMEM const char s_m_stop[] = "m_stop";
	
  /** Les entree sortie : all_startm_stop**/ 
		boolean all_start = false;
		boolean ev_all_start=false;
		boolean prior_all_start = false;
		
		PROGMEM const char s_all_start[] = "all_start";
	
 // generated by acceleo 

  /** Les entree sortie : all_stop**/ 
		boolean all_stop = false;
		boolean ev_all_stop=false;
		boolean prior_all_stop = false;
		
		PROGMEM const char s_all_stop[] = "all_stop";
	

 {
----------------------------------------------------------

 MOTOR : 
 SB : boolean
var FB: boolean
var M: boolean


   
   
       #define MOTOR 8// l'entree a change !! 
	
   
   
       #define SB 8// l'entree a change !! 
	
   
   
       #define FB 8// l'entree a change !! 
	
   
   
       #define M 8// l'entree a change !! 
	
   
   
       #define  8// l'entree a change !! 
	


   
       #define MOTOR 8// l'entree a change !! 
	
   
       #define SB 8// l'entree a change !! 
	
   
       #define FB 8// l'entree a change !! 
	
   
       #define M 8// l'entree a change !! 
	
   
       #define  8// l'entree a change !! 
	

