#include <Arduino.h>
#include "runner.h"
#include "io.h"

unsigned long outcount = 0;

 // generated by acceleo 

  /** Les entree sortie : master_start**/ 
		boolean master_start = false;
		boolean ev_master_start=false;
		boolean prior_master_start = false;
		
		PROGMEM const char s_master_start[] = "master_start";
	
 // generated by acceleo 

  /** Les entree sortie : sb_startmaster_stop**/ 
		boolean sb_start = false;
		boolean ev_sb_start=false;
		boolean prior_sb_start = false;
		
		PROGMEM const char s_sb_start[] = "sb_start";
	
  /** Les entree sortie : sb_startmaster_stop**/ 
		boolean master_stop = false;
		boolean ev_master_stop=false;
		boolean prior_master_stop = false;
		
		PROGMEM const char s_master_stop[] = "master_stop";
	
 // generated by acceleo 

  /** Les entree sortie : sb_stop**/ 
		boolean sb_stop = false;
		boolean ev_sb_stop=false;
		boolean prior_sb_stop = false;
		
		PROGMEM const char s_sb_stop[] = "sb_stop";
	


void resetEvents() {
 // generated by acceleo
	  master_start = false;
 // generated by acceleo
	  sb_start = false;
	  master_stop = false;
 // generated by acceleo
	  sb_stop = false;
}

boolean in_ev(boolean v, boolean *p) {
	boolean result = !*p && v;
	*p = v;
	return result;
}

void acquireInputs() {

		in_event(master_start);
		debug_event(master_start);
		in_event(sb_start);
		debug_event(sb_start);
		in_event(master_stop);
		debug_event(master_stop);
		in_event(sb_stop);
		debug_event(sb_stop);
	
}


void resetInputs_nu() {
  
 // generated by acceleo
		master_start = false;
 // generated by acceleo
		sb_start = false;
		master_stop = false;
 // generated by acceleo
		sb_stop = false;

}




void applyOutputs_nu() {
	//TODO extract from command queue ?
}

#ifdef CONSOLE_PARSER


boolean input_kb(int k) { // a changer apres la transformation ! 
	StateMachine_setEvent();
    
// decomenter le code suivant avec votre changement : 
/*

	if (k == 1) // la touche 1 
		master_start = true;
	else if (k==2) // la touche 2
		master_stop = true;
	else
		return false;
	return true;
*/
}

boolean input_cmd_str(char* cmd) {
	//event = true;
	StateMachine_setEvent();


 // generated by acceleo
		if (strstr_P(cmd, s_master_start) == cmd){
			master_start=true;
		return true;
		}
 // generated by acceleo
		if (strstr_P(cmd, s_sb_start) == cmd){
			sb_start=true;
		return true;
		}
		if (strstr_P(cmd, s_master_stop) == cmd){
			master_stop=true;
		return true;
		}
 // generated by acceleo
		if (strstr_P(cmd, s_sb_stop) == cmd){
			sb_stop=true;
		return true;
		}

  return false;
}

#endif



void out(int outp, boolean value,int i) {
	outcount++;
	digitalWrite(outp, value);
}

void init_io() {
	//out(MOTOR, false);
}

